org: adrianurbinamendoza
service: erd-generator

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  timeout: 30
  iam:
    role: arn:aws:iam::254780740814:role/LabRole
  ecr:
    images:
      entidad_relacion:
        path: .  


functions:
  generate-erd:
    image:
      name: entidad_relacion
    events:
      - http:
          path: /erd
          method: post
          cors: true
          integration: lambda-proxy