org: adrianurbinamendoza
service: diagrama-hack

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.9
  timeout: 30
  region: us-east-1
  iam:
    role: arn:aws:iam::254780740814:role/LabRole
  environment:
    DIAGRAM_BUCKET: cad-diagrama
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource:
        - arn:aws:s3:::cad-diagrama/*

functions:
  registrar:
    handler: UserCreate.lambda_handler
    events:
      - http:
          path: /usuarios/registrar
          method: post
          cors: true
          integration: lambda-proxy

  login:
    handler: UserLogin.lambda_handler
    events:
      - http:
          path: /usuarios/login
          method: post
          cors: true
          integration: lambda-proxy

  authorizer:
    handler: UserValidar.lambda_handler

  generarDiagrama:
    handler: DiagramGen.lambda_handler
    # layers:
    #   - { Ref: GraphvizPythonLambdaLayer }
    events:
      - http:
          path: /diagramas
          method: post
          cors: true
          integration: lambda-proxy
          authorizer:
            type: request
            authorizerId:
              Fn::GetAtt:
                - AuthorizerLambdaFunction
                - Arn

resources:
  Resources:
    AbUsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ab_usuarios
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    AbTokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ab_tokens_acceso
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
          - AttributeName: tenant_id
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH
          - AttributeName: tenant_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: expires_ts
          Enabled: true

    DiagramasBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: cad-diagrama
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins: ["*"]
              AllowedMethods: ["GET","PUT","POST"]
              AllowedHeaders: ["*"]
