org: adrianurbinamendoza
service: diagrama-hack

plugins:
  - serverless-python-requirements
  - serverless-aws-documentation

provider:
  name: aws
  runtime: python3.9
  timeout: 30
  region: us-east-1
  iam:
    role: arn:aws:iam::254780740814:role/LabRole

custom:
  pythonRequirements:
    dockerizePip: true
    layer: false
    useDownloadCache: false
    useStaticCache: false

  documentation:
    api:
      info:
        version: '1.0.0'
        title: Abarrotes Usuarios API
        description: API para registrar, validar y autenticar usuarios
    models:
      - name: UserRequest
        contentType: 'application/json'
        schema:
          type: object
          properties:
            user_id:
              type: string
              description: "User ID (correo electrónico)"
            tenant_id:
              type: string
              description: "Tenant ID (nombre del establecimiento)"
            password:
              type: string
              description: "User password"
      - name: UserValidateRequest
        contentType: 'application/json'
        schema:
          type: object
          properties:
            token:
              type: string
              description: "Token por validar al lambda authorizer"
            tenant_id:
              type: string
              description: "Tenant ID (nombre del establecimiento)"

functions:
  registrar:
    handler: UserCreate.lambda_handler
    documentation:
      summary: Registrar usuario
      requestModels:
        'application/json': UserRequest
    events:
      - http:
          path: /usuarios/registrar
          method: post
          cors: true
          integration: lambda

  validar:
    handler: UserValidar.lambda_handler
    documentation:
      summary: Validar usuario
      requestModels:
        'application/json': UserRequest
    events:
      - http:
          path: /usuarios/validar
          method: post
          cors: true
          integration: lambda

  login:
    handler: UserLogin.lambda_handler
    documentation:
      summary: Login usuario
      requestModels:
        'application/json': UserRequest
    events:
      - http:
          path: /usuarios/login
          method: post
          cors: true
          integration: lambda

  swaggerui:
    handler: swagger.lambda_handler
    events:
      - http:
          path: /docs
          method: get
          cors: true

  openapi:
    handler: swagger.openapi_handler
    events:
      - http:
          path: /openapi.yaml
          method: get
          cors: true
