org: adrianurbinamendoza
service: diagram-usuarios

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.13
  timeout: 30
  region: us-east-1
  iam:
    role: arn:aws:iam::254780740814:role/LabRole
  environment:
  TABLE_NAME: usuarios

custom:
  pythonRequirements:
    dockerizePip: true
    layer: false
    useDownloadCache: false
    useStaticCache: false

functions:
  registrar:
    handler: UserCreate.lambda_handler
    documentation:
      summary: Registrar usuario
      requestModels:
        'application/json': UserRequest
    events:
      - http:
          path: /usuarios/registrar
          method: post
          cors: true
          integration: lambda

  validar:
    handler: UserValidar.lambda_handler
    documentation:
      summary: Validar usuario
      requestModels:
        'application/json': UserRequest
    events:
      - http:
          path: /usuarios/validar
          method: post
          cors: true
          integration: lambda

  login:
    handler: UserLogin.lambda_handler
    documentation:
      summary: Login usuario
      requestModels:
        'application/json': UserRequest
    events:
      - http:
          path: /usuarios/login
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    Usuarios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    TokenUsuarios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}-token
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: token_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: token
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST