org: nayeliguzman
service: json-diagram-generator

provider:
  name: aws
  region: us-east-1
  iam:
    role: arn:aws:iam::254780740814:role/LabRole
    roleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:PutObjectAcl
          - s3:GetObject
        Resource: "arn:aws:s3:::*/*"

  ecr:
    images:
      generate-diagram:
        path: .

functions:
  generate-diagram:
    image:
      name: generate-diagram
    events:
      - http:
          path: /generate-diagram
          method: post
          cors: true
          integration: lambda-proxy
