org: adrianurbinamendoza
service: json-diagram-generator

provider:
  name: aws
  runtime: python3.13
  timeout: 30
  region: us-east-1
  iam:
    role: arn:aws:iam::254780740814:role/LabRole
  ecr:
    images:
      generate-diagram:
        path: .

functions:
  generate-diagram:
    image:
      name: generate-diagram
    events:
      - http:
          path: /generate-diagram
          method: post
          cors: true
          integration: lambda-proxy
