org: adrianurbinamendoza
service: conversion

provider:
  name: aws
  runtime: python3.13
  timeout: 30
  region: us-east-1
  iam:
    role: arn:aws:iam::254780740814:role/LabRole
  ecr:
    images:
      aws:
        path: .  

functions:
  conversion-aws:
    image:
      name: aws
    events:
      - http:
          path: /conversion/aws
          method: post
          cors: true
          integration: lambda-proxy
